// ────────────────────────────────────────────────────────────────────────
// Executive narrative generation.
//
// Calls Claude Opus 4.7 to turn raw KPI numbers into a 1-2 paragraph
// summary suitable for a monthly report's executive summary section.
// Falls back to a deterministic template when ANTHROPIC_API_KEY is
// missing — so dev environments without API access still render
// reports, and demos stay reproducible.
//
// Surface choice — Opus 4.7 + no thinking + max_tokens=1024:
//   • Opus 4.7 is the platform default (claude-api skill guidance).
//   • Thinking is off (Opus 4.7 default) — narrative is well-bounded
//     and benefits more from accurate retrieval-style writing than
//     extended reasoning.
//   • Short output → no streaming needed (well under the 16K SDK
//     timeout threshold).
//   • System prompt is short (~600 tokens) — below Opus 4.7's
//     4096-token cacheable-prefix minimum, so prompt caching would
//     silently no-op. Skipped. If we expand the system prompt with
//     guidance docs in future, add `cache_control: {type: "ephemeral"}`
//     to the system block then.
// ────────────────────────────────────────────────────────────────────────

import Anthropic from "@anthropic-ai/sdk";
import type { KpiResult } from "./kpi-engine";
import { KPI_REGISTRY, type KpiCode } from "./kpi-registry";

const MODEL = "claude-opus-4-7";
const MAX_TOKENS = 1024;

const SYSTEM_PROMPT = `You are the lead safety analyst at an Indian cement manufacturing group, writing the executive summary section of a monthly safety performance report.

Audience: Plant Head, Corporate HSE, and CFO. They read the KPI table directly — your job is to interpret the numbers, not restate them.

Style:
- 1 to 2 paragraphs, ~120-180 words total
- Professional, factual, calibrated. Highlight improvements AND concerns equally. Do not editorialise.
- Cite specific KPIs by name (LTIFR, Near Miss Rate, etc.) with their values when relevant
- Reference IS 3786 / OSHA only when contextually meaningful — do NOT name-drop standards as filler
- End with ONE clear priority for the next month — concrete, actionable

Hard rules:
- NEVER invent incidents, names, or numbers. Use only what's in the data provided.
- NEVER use phrases like "we are committed to safety" or "safety is our priority" — empty corporate language.
- NEVER use Markdown headers (no #), bullets, or formatting — plain prose paragraphs only.
- If a KPI worsened, name it directly. If a KPI improved, name it directly. No softening.`;

export interface NarrativeInput {
  plantName: string;
  plantCode: string;
  reportingPeriodLabel: string; // e.g. "April 2026" or "FY26 Q1"
  kpis: Record<string, KpiResult>;
  /** Optional comparison period — last month, or last year same month. */
  priorKpis?: Record<string, KpiResult>;
  priorPeriodLabel?: string;
  /** Notable events the model should weave in — pre-summarised incident
   *  count, unlock events, statutory deadlines. */
  contextNotes?: string;
}

export interface NarrativeResult {
  narrative: string;
  /** Whether the narrative came from Claude or the deterministic
   *  template fallback. UI can show a "generated by AI" indicator. */
  source: "claude" | "template";
  /** Set when the engine fell back due to a recoverable failure
   *  (missing key, timeout, API error). UI surfaces this gracefully. */
  fallbackReason?: string;
  /** Token usage when source === "claude". Useful for cost tracking. */
  tokenUsage?: { input: number; output: number };
}

// Cache the Anthropic client at module level — both for cold-start
// latency and so the singleton-with-key pattern matches the rest of
// the platform's external clients (Prisma, etc.).
const anthropic = process.env.ANTHROPIC_API_KEY
  ? new Anthropic({ apiKey: process.env.ANTHROPIC_API_KEY })
  : null;

export async function generateMonthlyNarrative(
  input: NarrativeInput
): Promise<NarrativeResult> {
  if (!anthropic) {
    return {
      narrative: buildTemplateNarrative(input),
      source: "template",
      fallbackReason:
        "ANTHROPIC_API_KEY not configured — using deterministic template. Set the env var to enable AI-generated narratives."
    };
  }

  const userPrompt = buildUserPrompt(input);

  try {
    const response = await anthropic.messages.create({
      model: MODEL,
      max_tokens: MAX_TOKENS,
      system: SYSTEM_PROMPT,
      messages: [{ role: "user", content: userPrompt }]
    });

    const text = response.content
      .filter((b): b is Anthropic.TextBlock => b.type === "text")
      .map((b) => b.text)
      .join("\n")
      .trim();

    if (!text) {
      // Model returned no text — fall back rather than render empty.
      return {
        narrative: buildTemplateNarrative(input),
        source: "template",
        fallbackReason: "Claude returned an empty response"
      };
    }

    return {
      narrative: text,
      source: "claude",
      tokenUsage: {
        input: response.usage.input_tokens,
        output: response.usage.output_tokens
      }
    };
  } catch (e: any) {
    // Graceful degrade — don't fail the whole report because the API
    // is rate-limited or temporarily down. The deterministic
    // template is publication-quality on its own.
    return {
      narrative: buildTemplateNarrative(input),
      source: "template",
      fallbackReason: `Claude API error: ${e?.message ?? "unknown"}`
    };
  }
}

// ── User prompt assembly ─────────────────────────────────────────

function buildUserPrompt(input: NarrativeInput): string {
  const lines: string[] = [
    `Plant: ${input.plantName} (${input.plantCode})`,
    `Period: ${input.reportingPeriodLabel}`,
    "",
    "KPI snapshot:",
    ...formatKpis(input.kpis)
  ];

  if (input.priorKpis && input.priorPeriodLabel) {
    lines.push("", `Comparison — ${input.priorPeriodLabel}:`);
    lines.push(...formatKpis(input.priorKpis));
  }

  if (input.contextNotes) {
    lines.push("", "Context for this period:", input.contextNotes);
  }

  lines.push(
    "",
    "Write the executive summary for this report. 1-2 paragraphs, plain prose, professional tone, end with one priority for next month."
  );

  return lines.join("\n");
}

function formatKpis(kpis: Record<string, KpiResult>): string[] {
  const out: string[] = [];
  for (const code of Object.keys(kpis)) {
    const k = kpis[code];
    if (!k) continue;
    const band = k.band ? ` [${k.band}]` : "";
    out.push(`  ${k.kpiName} (${k.kpiCode}): ${k.formattedValue}${band}`);
  }
  return out;
}

// ── Deterministic template fallback ──────────────────────────────

/**
 * Produces a plausible executive summary from the raw KPI numbers
 * without any LLM. Used when ANTHROPIC_API_KEY is unset (dev/CI), or
 * when the Claude API errors out. Output is intentionally similar in
 * structure to the AI version so reports look consistent regardless
 * of source.
 */
function buildTemplateNarrative(input: NarrativeInput): string {
  const ltifr = input.kpis["LTIFR"];
  const trifr = input.kpis["TRIFR"];
  const nmRate = input.kpis["NEAR_MISS_RATE"];
  const sev = input.kpis["SEVERITY_RATE"];
  const days = input.kpis["DAYS_SINCE_LAST_LTI"];

  const parts: string[] = [];

  // Lead: headline LTIFR + days-since framing
  // Every clause below is gated on `value != null`, not merely on the KPI being
  // present. A narrative is the one place a false zero does the most damage: it
  // turns "we could not measure this" into a sentence a director will quote.
  if (ltifr && ltifr.value != null) {
    const band = ltifr.band?.replace(/_/g, " ").toLowerCase() ?? "in range";
    parts.push(
      `${input.plantName} reported LTIFR of ${ltifr.formattedValue} (${band}) for ${input.reportingPeriodLabel}.`
    );
  } else if (ltifr) {
    parts.push(
      `LTIFR could not be computed for ${input.plantName} in ${input.reportingPeriodLabel} — ${ltifr.unavailableReason}. Treat the frequency rates below as unavailable rather than favourable.`
    );
  }
  if (days && days.value != null && days.value > 0) {
    parts.push(`Days since last LTI: ${Math.round(days.value)}.`);
  }
  if (trifr && trifr.value != null) {
    parts.push(
      `TRIFR stands at ${trifr.formattedValue}, reflecting the combined recordable-injury frequency across the plant.`
    );
  }
  if (sev && sev.value != null) {
    parts.push(`Severity rate per IS 3786 came in at ${sev.formattedValue}.`);
  }

  // Mid: leading-indicator context
  if (nmRate && nmRate.value != null) {
    const dir = nmRate.higherIsBetter ? "reporting culture" : "exposure";
    parts.push(
      `Near miss reporting rate was ${nmRate.formattedValue} per million hours — a leading indicator of ${dir}.`
    );
  }

  if (input.contextNotes) {
    parts.push(input.contextNotes);
  }

  // Closing — priority for next month
  if (ltifr?.band === "POOR" || trifr?.band === "POOR") {
    parts.push(
      "Priority for next month: deep-dive root cause analysis on the recordable incidents and accelerated CAPA closure to bend the curve."
    );
  } else if (nmRate && nmRate.value != null && nmRate.value < (nmRate.benchmarks?.average ?? 200)) {
    parts.push(
      "Priority for next month: drive near-miss reporting up through supervisor coaching — leading indicator below the average band."
    );
  } else {
    parts.push(
      "Priority for next month: maintain the current rhythm of inspection and training discipline; address any aging CAPAs before next cycle."
    );
  }

  return parts.join(" ");
}
