"use client";

// iconKey (kebab-case, stored on CaptureTaxonomy rows) → lucide component.
// Explicit import map — `import * as icons` would defeat tree-shaking and pull
// the whole lucide library into the low-end-device bundle. The map covers
// every iconKey used by prisma/capture-taxonomy-data.ts (verified against
// lucide-react 0.344.0); unknown keys fall back to AlertTriangle so a
// taxonomy edit can never blank a tile.

import {
  AlertTriangle,
  Archive,
  Armchair,
  BatteryLow,
  Bell,
  BellOff,
  Box,
  Boxes,
  Briefcase,
  Brush,
  Cable,
  Calendar,
  ClipboardList,
  Clock,
  Cog,
  Construction,
  DoorClosed,
  DoorOpen,
  Droplets,
  Ear,
  Eye,
  EyeOff,
  Factory,
  Fan,
  FastForward,
  Fence,
  FileCheck,
  FileText,
  FireExtinguisher,
  Flame,
  FlaskConical,
  FlaskRound,
  Footprints,
  Gauge,
  Glasses,
  GraduationCap,
  Hammer,
  Hand,
  HardHat,
  Haze,
  HeartPulse,
  History,
  Home,
  Infinity as InfinityIcon,
  Lamp,
  Languages,
  Layers,
  LayoutGrid,
  LifeBuoy,
  Lightbulb,
  ListChecks,
  Lock,
  MapPin,
  Megaphone,
  MessageSquare,
  Moon,
  MoveDown,
  Package,
  Paintbrush,
  PersonStanding,
  Plug,
  PlugZap,
  Power,
  RefreshCw,
  Repeat,
  Replace,
  Scale,
  Scissors,
  Search,
  Shield,
  ShieldAlert,
  ShieldCheck,
  ShieldOff,
  Shirt,
  ShoppingCart,
  Shuffle,
  Signpost,
  SprayCan,
  Thermometer,
  ThumbsDown,
  Timer,
  Trash2,
  TrendingUp,
  Truck,
  Unlock,
  UserX,
  Users,
  Volume2,
  Wallet,
  Weight,
  Wind,
  Wrench,
  Zap,
  ZapOff,
  type LucideIcon,
} from "lucide-react";

const ICON_MAP: Record<string, LucideIcon> = {
  "alert-triangle": AlertTriangle,
  archive: Archive,
  armchair: Armchair,
  "battery-low": BatteryLow,
  bell: Bell,
  "bell-off": BellOff,
  box: Box,
  boxes: Boxes,
  briefcase: Briefcase,
  brush: Brush,
  cable: Cable,
  calendar: Calendar,
  "clipboard-list": ClipboardList,
  clock: Clock,
  cog: Cog,
  construction: Construction,
  "door-closed": DoorClosed,
  "door-open": DoorOpen,
  droplets: Droplets,
  ear: Ear,
  eye: Eye,
  "eye-off": EyeOff,
  factory: Factory,
  fan: Fan,
  "fast-forward": FastForward,
  fence: Fence,
  "file-check": FileCheck,
  "file-text": FileText,
  "fire-extinguisher": FireExtinguisher,
  flame: Flame,
  "flask-conical": FlaskConical,
  "flask-round": FlaskRound,
  footprints: Footprints,
  gauge: Gauge,
  glasses: Glasses,
  "graduation-cap": GraduationCap,
  hammer: Hammer,
  hand: Hand,
  "hard-hat": HardHat,
  haze: Haze,
  "heart-pulse": HeartPulse,
  history: History,
  home: Home,
  infinity: InfinityIcon,
  lamp: Lamp,
  languages: Languages,
  layers: Layers,
  "layout-grid": LayoutGrid,
  "life-buoy": LifeBuoy,
  lightbulb: Lightbulb,
  "list-checks": ListChecks,
  lock: Lock,
  "map-pin": MapPin,
  megaphone: Megaphone,
  "message-square": MessageSquare,
  moon: Moon,
  "move-down": MoveDown,
  package: Package,
  paintbrush: Paintbrush,
  "person-standing": PersonStanding,
  plug: Plug,
  "plug-zap": PlugZap,
  power: Power,
  "refresh-cw": RefreshCw,
  repeat: Repeat,
  replace: Replace,
  scale: Scale,
  scissors: Scissors,
  search: Search,
  shield: Shield,
  "shield-alert": ShieldAlert,
  "shield-check": ShieldCheck,
  "shield-off": ShieldOff,
  shirt: Shirt,
  "shopping-cart": ShoppingCart,
  shuffle: Shuffle,
  signpost: Signpost,
  "spray-can": SprayCan,
  thermometer: Thermometer,
  "thumbs-down": ThumbsDown,
  timer: Timer,
  "trash-2": Trash2,
  "trending-up": TrendingUp,
  truck: Truck,
  unlock: Unlock,
  "user-x": UserX,
  users: Users,
  "volume-2": Volume2,
  wallet: Wallet,
  weight: Weight,
  wind: Wind,
  wrench: Wrench,
  zap: Zap,
  "zap-off": ZapOff,
};

export function taxonomyIcon(iconKey: string | null | undefined): LucideIcon {
  if (!iconKey) return AlertTriangle;
  return ICON_MAP[iconKey] ?? AlertTriangle;
}
